name: flutter_swiper_3
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 3.0.0
homepage: https://github.com/leandro-zanardi/flutter_swiper_3

dependencies:
  flutter:
    sdk: flutter


environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
